### ISSUE TITLE
linking to notes that contain the name of other notes

### ISSUE THREAD

**Issue by ghost** [tomboy-notes/tomboy#5] opened 2014-06-15 05:05 UTC
Hi.

I make 3 notes:
`Olga`
`Kay`
`Olga Kay`
However I cannot link to `Olga Kay` because it only links(automatically) to `Olga` and the word Kay is sometimes linked but most of the time is not. When it does link it links to `Kay`, but there's thus no way to link to `Olga Kay` note because the other two will take precedence somehow.

**EDIT:**
$ tomboy --version
Tomboy: A simple, easy to use desktop note-taking application.
Copyright © 2004-2007 Alex Graveley
<alex@beatniksoftware.com>

Copyright © 2004-2011 Others
Version 1.14.1
under linux manjaro 64bit with xfce4
Linux manji 3.12.20-1-MANJARO #1 SMP PREEMPT Tue May 20 16:54:28 EST 2014 x86_64 GNU/Linux

**Comment by alex-ter** [comment] 2016-08-01 19:30
@ghost, I'm doing some bug scrubbing, is this still actual for you?

**Comment by alex-ter** [comment] 2016-08-03 18:47
Ok, apparently "ghost" is a substitute account for deleted users :smiley: so I'm closing this one, if anyone faces this - please post here and I'll reopen it.

**Closed by alex-ter** 2016-08-03 18:47 UTC

**Comment by mlncn** [comment] 2017-07-01 14:46
@alex-ter This does happen with Version 1.14.1 which is the version still in Debian.  The steps to reproduce in the original bug report are correct, and i think the expected behavior is correct— the longest note name should win.

If i create a note "Alex Tereschenko" and a note "Alex Tereschenko rocks", when i type "Alex Tereschenko rocks" in a third note it should link to the longer phrase; instead it links to "Alex Tereschenko".

As an aside, is there a latest Debian repository that can be added and Tomboy installed from that so i'm testing a recent version?  I'm stuck on "sudo apt-get build-dep tomboy" (no package tomboy) of https://wiki.gnome.org/Apps/Tomboy/Developers so i'm quite a ways away from being useful.

**Comment by alex-ter** [comment] 2017-07-05 18:43
1.14 is quite old by all accounts, you'd realy want the latest one to try it, just too many things changed since then.

I don't know of any Debian build, sorry. Though I've tested building on Debian stable several months ago (the instructions were working back then). Are you saying there's no tomboy package there now at all? If so I'm afraid the best course of action would be to submit a request to distro maintainers to add it back. Also, it could be possible to single out specific dependencies to install (instead of build-dep shortcut)  but someone would have to do that...

**Comment by mlncn** [comment] 2017-07-05 19:23
So this is what Debian has:

https://packages.debian.org/sid/tomboy

With the cutting edge 'experimental' having 1.15.4-1

So for people on Debian, including Debian Mint, (and maybe Ubuntu?) to easily use any version of Tomboy that you have contributed to, it seems that having someone helping Debian itself be more up-to-date or maintaining package repositories separately will be needed.
