### ISSUE TITLE
Can't delete note. Hitting delete button is without effect.

### ISSUE THREAD

**Issue by feluxe** [tomboy-notes/tomboy#46] opened 2017-03-24 12:25 UTC
Hi there!

If I open a note and click on the delete button, the opened note will dispensary but still show up in the main Tomboy window. I can reopen the note as if nothing happened.

On the other hand, if I right-click on a note in the main window and choose "delete" it is deleted properly.

OS: Linux Mint (17 and 18) Cinnamon Desktop.

**Comment by davidbannon** [comment] 2017-03-24 23:11
Hello Feluxe, can you please tell us the version of Tomboy Notes you are 
using.

Click the icon, select "Search" and from that window, click "Help", then 
"About".

David

**Comment by alex-ter** [comment] 2017-03-25 19:41
Right, the version would be helpful. Thiss sounds like a bug I've fixed a while ago.

**Comment by feluxe** [comment] 2017-03-26 17:52
Version is `1.15.4`. I think Tomboy came pre-installed with Linux Mint 18.1. I have the issue since Mint 17.3. (that's where I started using Tomboy).

**Comment by alex-ter** [comment] 2017-03-27 09:38
Ok, so this is a duplicate of issue #13, which @davidbannon (not me - false memory) fixed and it was released in version 1.15.6. So @feluxe, you need to ask your distro's Tomboy package maintainers to update to the latest Tomboy release and you should be good.

**Closed** 2017-03-27 09:39 UTC
Labels: bug, duplicate
