### ISSUE TITLE
HTML-Export fails

### ISSUE THREAD

**Issue by V-H** [tomboy-notes/tomboy#25] opened 2016-11-11 18:10 UTC
Not all Notes will be exported. Export by Tools/Export/All Notebooks|Selected Notebook stop with message "The Files couldn't be saved in ... | Unknown Error" (translated from German).

Links in exported notes are not correct at all. Some Links point to the Note itself.

Linux Mint 17.3 Rosa

**Comment by davidbannon** [comment] 2016-11-11 22:51
V-H, that sounds disappointing in the extreme. I cannot replicate your problem, perhaps you can help narrow it down ?
My guess is there is 'something' in a particular note that triggers the problem. Can you tell which note it failed on ?  One after the last successful one perhaps ? Or (depending on how many notes you have) could you try exporting one by one. You can also export by Notebook, so perhaps adding half your notes to a temp notebook and exporting can narrow it down ?
Sorry to mess you around but might be the only way we work out what is happening here.
David

**Comment by V-H** [comment] 2016-11-12 17:08
Hello David,

thanks a lot for your answer!

I've tried again to export some of my notebooks. Sometimes it works, sometimes not. Can't discover any reason.

But I found the log, listed below. Maybe you can read it, I don't know much enough about programming.

As far as I can figure it out, maybe there's a problem with links/references. But I don't understand what the problem is. May be there are links out of the actual exported notebook, so a NullReferenceException occurs?

I've installed an addon, which is able to "check" the link ("ExportToGraph") and acitivated it in tomboy - but I can't find any menu entry to use this plugin... 

Thanks,

Volker

Log:
12.11.2016 17:39:51 [INFO]: Activated export notebook to html
12.11.2016 17:40:00 [ERROR]: Exportieren war nicht möglich _[trslt: Exporting was not possible]_ : System.Xml.Xsl.XsltException: Custom function reported an error. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NullReferenceException: Object reference not set to an instance of an object
  at Tomboy.ExportAllApplicationAddin.ResolveRelativePath (Tomboy.Note note_from, System.String title_to) [0x00000] in <filename unknown>:0 
  at Tomboy.ExportToHtml.ExportAllTransformExtension.GetRelativePath (System.String title_to) [0x00000] in <filename unknown>:0 
  at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00000] in <filename unknown>:0 
  --- End of inner exception stack trace ---
  at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00000] in <filename unknown>:0 
  at System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) [0x00000] in <filename unknown>:0 
  at Mono.Xml.Xsl.XsltExtensionFunction.Invoke (Mono.Xml.Xsl.XsltCompiledContext xsltContext, System.Object[] args, System.Xml.XPath.XPathNavigator docContext) [0x00000] in <filename unknown>:0 
  --- End of inner exception stack trace ---
  at Mono.Xml.Xsl.XsltExtensionFunction.Invoke (Mono.Xml.Xsl.XsltCompiledContext xsltContext, System.Object[] args, System.Xml.XPath.XPathNavigator docContext) [0x00000] in <filename unknown>:0 
  at Mono.Xml.Xsl.XPFuncImpl.Invoke (System.Xml.Xsl.XsltContext xsltContext, System.Object[] args, System.Xml.XPath.XPathNavigator docContext) [0x00000] in <filename unknown>:0 
  at System.Xml.XPath.ExprFunctionCall.Evaluate (System.Xml.XPath.BaseIterator iter) [0x00000] in <filename unknown>:0 
  at System.Xml.XPath.Expression.EvaluateString (System.Xml.XPath.BaseIterator iter) [0x00000] in <filename unknown>:0 
  at System.Xml.XPath.CompiledExpression.EvaluateString (System.Xml.XPath.BaseIterator iter) [0x00000] in <filename unknown>:0 
  at System.Xml.XPath.XPathNavigator.EvaluateString (System.Xml.XPath.XPathExpression expr, System.Xml.XPath.XPathNodeIterator context, IXmlNamespaceResolver ctx) [0x00000] in <filename unknown>:0 
  at Mono.Xml.Xsl.XslTransformProcessor.EvaluateString (System.Xml.XPath.XPathExpression expr) [0x00000] in <filename unknown>:0 
  at Mono.Xml.Xsl.Operations.XslAvt+XPathAvtPart.Evaluate (Mono.Xml.Xsl.XslTransformProcessor p) [0x00000] in <filename unknown>:0 
  at Mono.Xml.Xsl.Operations.XslAvt.Evaluate (Mono.Xml.Xsl.XslTransformProcessor p) [0x00000] in <filename unknown>:0 
  at Mono.Xml.Xsl.Operations.XslLiteralElement+XslLiteralAttribute.Evaluate (Mono.Xml.Xsl.XslTransformProcessor p) [0x00000] in <filename unknown>:0 
  at Mono.Xml.Xsl.Operations.XslLiteralElement.Evaluate (Mono.Xml.Xsl.XslTransformProcessor p) [0x00000] in <filename unknown>:0 
  at Mono.Xml.Xsl.Operations.XslTemplateContent.Evaluate (Mono.Xml.Xsl.XslTransformProcessor p) [0x00000] in <filename unknown>:0 
  at Mono.Xml.Xsl.Operations.XslIf.EvaluateIfTrue (Mono.Xml.Xsl.XslTransformProcessor p) [0x00000] in <filename unknown>:0 
  at Mono.Xml.Xsl.Operations.XslChoose.Evaluate (Mono.Xml.Xsl.XslTransformProcessor p) [0x00000] in <filename unknown>:0 
  at Mono.Xml.Xsl.Operations.XslTemplateContent.Evaluate (Mono.Xml.Xsl.XslTransformProcessor p) [0x00000] in <filename unknown>:0 
  at Mono.Xml.Xsl.XslTemplate.EvaluateCore (Mono.Xml.Xsl.XslTransformProcessor p, System.Collections.Hashtable withParams) [0x00000] in <filename unknown>:0 
  at Mono.Xml.Xsl.XslTemplate.Evaluate (Mono.Xml.Xsl.XslTransformProcessor p, System.Collections.Hashtable withParams) [0x00000] in <filename unknown>:0 
  at Mono.Xml.Xsl.XslTransformProcessor.ApplyTemplates (System.Xml.XPath.XPathNodeIterator nodes, System.Xml.XmlQualifiedName mode, System.Collections.ArrayList withParams) [0x00000] in <filename unknown>:0 
  at Mono.Xml.Xsl.XslDefaultNodeTemplate.Evaluate (Mono.Xml.Xsl.XslTransformProcessor p, System.Collections.Hashtable withParams) [0x00000] in <filename unknown>:0 
  at Mono.Xml.Xsl.XslTransformProcessor.ApplyTemplates (System.Xml.XPath.XPathNodeIterator nodes, System.Xml.XmlQualifiedName mode, System.Collections.ArrayList withParams) [0x00000] in <filename unknown>:0 
  at Mono.Xml.Xsl.Operations.XslApplyTemplates.Evaluate (Mono.Xml.Xsl.XslTransformProcessor p) [0x00000] in <filename unknown>:0 
  at Mono.Xml.Xsl.Operations.XslTemplateContent.Evaluate (Mono.Xml.Xsl.XslTransformProcessor p) [0x00000] in <filename unknown>:0 
  at Mono.Xml.Xsl.Operations.XslLiteralElement.Evaluate (Mono.Xml.Xsl.XslTransformProcessor p) [0x00000] in <filename unknown>:0 
  at Mono.Xml.Xsl.Operations.XslTemplateContent.Evaluate (Mono.Xml.Xsl.XslTransformProcessor p) [0x00000] in <filename unknown>:0 
  at Mono.Xml.Xsl.XslTemplate.EvaluateCore (Mono.Xml.Xsl.XslTransformProcessor p, System.Collections.Hashtable withParams) [0x00000] in <filename unknown>:0 
  at Mono.Xml.Xsl.XslTemplate.Evaluate (Mono.Xml.Xsl.XslTransformProcessor p, System.Collections.Hashtable withParams) [0x00000] in <filename unknown>:0 
  at Mono.Xml.Xsl.XslTransformProcessor.ApplyTemplates (System.Xml.XPath.XPathNodeIterator nodes, System.Xml.XmlQualifiedName mode, System.Collections.ArrayList withParams) [0x00000] in <filename unknown>:0 
  at Mono.Xml.Xsl.Operations.XslApplyTemplates.Evaluate (Mono.Xml.Xsl.XslTransformProcessor p) [0x00000] in <filename unknown>:0 
  at Mono.Xml.Xsl.Operations.XslTemplateContent.Evaluate (Mono.Xml.Xsl.XslTransformProcessor p) [0x00000] in <filename unknown>:0 
  at Mono.Xml.Xsl.XslTemplate.EvaluateCore (Mono.Xml.Xsl.XslTransformProcessor p, System.Collections.Hashtable withParams) [0x00000] in <filename unknown>:0 
  at Mono.Xml.Xsl.XslTemplate.Evaluate (Mono.Xml.Xsl.XslTransformProcessor p, System.Collections.Hashtable withParams) [0x00000] in <filename unknown>:0 
  at Mono.Xml.Xsl.XslTransformProcessor.ApplyTemplates (System.Xml.XPath.XPathNodeIterator nodes, System.Xml.XmlQualifiedName mode, System.Collections.ArrayList withParams) [0x00000] in <filename unknown>:0 
  at Mono.Xml.Xsl.Operations.XslApplyTemplates.Evaluate (Mono.Xml.Xsl.XslTransformProcessor p) [0x00000] in <filename unknown>:0 
  at Mono.Xml.Xsl.Operations.XslTemplateContent.Evaluate (Mono.Xml.Xsl.XslTransformProcessor p) [0x00000] in <filename unknown>:0 
  at Mono.Xml.Xsl.Operations.XslLiteralElement.Evaluate (Mono.Xml.Xsl.XslTransformProcessor p) [0x00000] in <filename unknown>:0 
  at Mono.Xml.Xsl.Operations.XslTemplateContent.Evaluate (Mono.Xml.Xsl.XslTransformProcessor p) [0x00000] in <filename unknown>:0 
  at Mono.Xml.Xsl.Operations.XslLiteralElement.Evaluate (Mono.Xml.Xsl.XslTransformProcessor p) [0x00000] in <filename unknown>:0 
  at Mono.Xml.Xsl.Operations.XslTemplateContent.Evaluate (Mono.Xml.Xsl.XslTransformProcessor p) [0x00000] in <filename unknown>:0 
  at Mono.Xml.Xsl.XslTemplate.EvaluateCore (Mono.Xml.Xsl.XslTransformProcessor p, System.Collections.Hashtable withParams) [0x00000] in <filename unknown>:0 
  at Mono.Xml.Xsl.XslTemplate.Evaluate (Mono.Xml.Xsl.XslTransformProcessor p, System.Collections.Hashtable withParams) [0x00000] in <filename unknown>:0 
  at Mono.Xml.Xsl.XslTransformProcessor.ApplyTemplates (System.Xml.XPath.XPathNodeIterator nodes, System.Xml.XmlQualifiedName mode, System.Collections.ArrayList withParams) [0x00000] in <filename unknown>:0 
  at Mono.Xml.Xsl.XslTransformProcessor.Process (System.Xml.XPath.XPathNavigator root, Mono.Xml.Xsl.Outputter outputtter, System.Xml.Xsl.XsltArgumentList args, System.Xml.XmlResolver resolver) [0x00000] in <filename unknown>:0 
  at System.Xml.Xsl.XslTransform.Transform (System.Xml.XPath.XPathNavigator input, System.Xml.Xsl.XsltArgumentList args, System.IO.TextWriter output, System.Xml.XmlResolver resolver) [0x00000] in <filename unknown>:0 
  at System.Xml.Xsl.XslTransform.Transform (IXPathNavigable input, System.Xml.Xsl.XsltArgumentList args, System.IO.TextWriter output) [0x00000] in <filename unknown>:0 
  at Tomboy.ExportToHtml.ExportToHtmlApplicationAddin.WriteHTMLForNote (System.IO.TextWriter writer, Tomboy.Note note) [0x00000] in <filename unknown>:0 
  at Tomboy.ExportToHtml.ExportToHtmlApplicationAddin.ExportSingleNote (Tomboy.Note note, System.String output_folder) [0x00000] in <filename unknown>:0 
  at Tomboy.ExportAllApplicationAddin.ExportNotesInList (System.Collections.Generic.List`1 note_list, System.String output_folder) [0x00000] in <filename unknown>:0 
  at Tomboy.ExportAllApplicationAddin.ExportNotebookButtonClicked (System.Object sender, System.EventArgs args) [0x00000] in <filename unknown>:0 
12.11.2016 17:40:12 [ERROR]: Unbekannter Fehler._[trslt: Unknown Error]_
12.11.2016 17:40:58 [INFO]: Activated export notebook to html
12.11.2016 17:41:33 [INFO]: Activated export notebook to html

**Comment by alex-ter** [comment] 2016-11-12 19:59
Looks like it chokes on resolving either some path or link when exporting the note. I'll take a deeper look tomorrow. Thanks David for chiming in!

**Comment by alext-mkrs** [comment] 2016-11-13 15:38
I've taken a look at the respective piece of code and I don't see anything apparently problematic, but there are some places where a null object may creep in causing something like this.

**Volker**, could you please run Tomboy in a debug mode by executing `tomboy --debug` in the console, reproduce the issue, close Tomboy and attach the `~/.config/tomboy/tomboy.log` file here? It should show in more detail at which exact place does it fail.

**Comment by V-H** [comment] 2016-11-13 16:05
Hello Alex,

thanks for your help. Log is attached...

Greetings,

Volker
[tomboylog.txt](https://github.com/tomboy-notes/tomboy/files/587848/tomboylog.txt)

**Comment by robpvn** [comment] 2016-11-14 08:24
I wrote the resolveRelativePaths code five years ago, so just wanted to say drop off some info: The intention of the method is to resolve the paths between notes when exported, that is since every notebook is saved as its own folder, links between notes across notebooks have to be turned into relative paths between folders. (../someothernotebook/linkednot.html). 

Looking at the log, the problem specifically occurs when you try to export the note 'Ohne Titel - E.T.A. Hoffmann', which probably has a corrupted link. You should check this note and seee if all the links from it work!

What I think is the crash bug:
In the code 
`    Note note_to = manager.Find (title_to);`
`    string title_from = SanitizeNoteTitle (note_from.Title);`
`    title_to = SanitizeNoteTitle (note_to.Title);`

manager.Find can return null if there is no note by that title, and this isn't null-checked before being used to get note_to.Title.

**Comment by V-H** [comment] 2016-11-14 08:52
Hello robpvn!

Thanks for your comment. Indeed, there is a link in "Ohne Titel - E.T.A. Hoffmann". This link points to a note in another Notebook. I clicked that link, and the note openend. The difference I checked is, that in the source note the text is "ich" - while the linked noted is titled with "Ich".

I've attached the log of the clicking action and a screenshot, showing some messages in the console, which don't appear in the log.

Thanks,
Volker

![screenshot at 2016-11-14 09 46 11](https://cloud.githubusercontent.com/assets/5627518/20258326/761ca4dc-aa4f-11e6-9f76-ab4bbc260e76.png)
[tomboylog.txt](https://github.com/tomboy-notes/tomboy/files/588741/tomboylog.txt)

**Comment by V-H** [comment] 2016-11-14 11:07
I'm able to export the note "Ohne Titel - E.T.A. Hoffmann" to HTML using the notes toolbox. The link "ich" in the HTML-page shows:  "Ohne Titel - E_T_A_ Hoffmann#ich".

In the note "Ich" the text "ich" is also found, without link.

I can export "Ich" with the note-toolbox.

Greetings,

Volker

**Comment by alex-ter** [comment] 2016-11-14 12:07
Thanks Rob, that's exactly the place I suspected :), appreciate your clarification. Volker, could you please try changing the link to be spelled exactly the way that other note is named (or vice versa - change the note's title to all-lowercase "ich")? And try exporting all? I don't have the code in front of me right now, but I guess that relative path resolution function is not called when you export just single notes.

**Comment by V-H** [comment] 2016-11-14 13:06
I changed the link - it works.
BUT:
I set it back to "ich" - it works, too.

So I tried to export another Notebook. Failed. It also contained a note which links to "Ich", written as "ich" in the note. So I changed it to "Ich". But it doesn't work, the process breaks at the same note. The notebook, that "Ich" contains, can be exported without error. Within this notebook are notes, that link to "Ich" - written as "ich"

Debug-Log of failed export:
[tomboylog.txt](https://github.com/tomboy-notes/tomboy/files/589274/tomboylog.txt)

**Comment by alex-ter** [comment] 2016-11-14 20:25
Thanks. Exporting a notebook with intra-notebook links would not trigger that function, because the relative path is well-known in this case (`./<notename`). Okay, thanks a lot for information pieces you've posted, I think I have enough information to try and reproduce it here, let me experiment a bit and get back to you.

**Comment by V-H** [comment] 2016-11-15 11:10
Thank you!

**Closed** 2016-11-20 17:43 UTC
Labels: bug

**Comment by alex-ter** [comment] 2016-11-20 17:50
So at the end of the day that was namely that was the piece of code I suspected and Rob has pointed to.

It requires a note to have a link, which is not marked as "broken" by Tomboy, but at the same time the destination note for that link does not exist.

Link's letter case is not important, because when looking for a note to create a path, both the link text and checked note's title are set to lowercase in `Find()`. So it must be a genuinely non-existing note. Not sure why correcting just the case helped in the first situation - it should have worked right away. In the second case the failing note probably has such a broken link, you can check it by clicking it.

In any case - the fix is in the repo and will be released as a part of 1.15.6, then you should be able to either compile it by yourself, Volker, or (in your specific case) rather submit a request to Mint maintainers to update Tomboy version there.

**Comment by V-H** [comment] 2016-11-21 08:40
Thank you, good bye...
